In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import linregress

In [2]:
nav_df = pd.read_csv("../data/processed/clean_nav_history.csv")
benchmark_df = pd.read_csv("../data/raw/benchmark_indices.csv")

print(nav_df.shape)
print(benchmark_df.shape)

(364, 3)
(8050, 3)

In [3]:
nav_df['date'] = pd.to_datetime(nav_df['date'])

nav_df = nav_df.sort_values(
    ['amfi_code', 'date']
)

nav_df['daily_return'] = (
    nav_df.groupby('amfi_code')['nav']
          .pct_change()
)

nav_df.head()

     amfi_code       date         nav  daily_return
182     118632 2024-01-01  113.549277           NaN
183     118632 2024-01-02   44.439543     -0.608632
184     118632 2024-01-03   62.558956      0.407732
185     118632 2024-01-04   77.409186      0.237380
186     118632 2024-01-05  109.904166      0.419782

In [4]:
rf = 0.065

sharpe_df = (
    nav_df.groupby('amfi_code')['daily_return']
    .agg(['mean','std'])
    .reset_index()
)

sharpe_df['sharpe_ratio'] = (
    ((sharpe_df['mean'] * 252) - rf)
    /
    (sharpe_df['std'] * np.sqrt(252))
)

sharpe_df

   amfi_code      mean       std  sharpe_ratio
0     118632  0.662615  2.003746      5.247465
1     119551  0.571829  1.850029      4.904469
2     120503  0.529294  1.533608      5.476094
3     125497  0.271637  0.888800      4.846986